export let travelPlaces = [
    "Paris, France",
    "Kyoto, Japan",
    "Santorini, Greece",
    "Banff National Park, Canada",
    "Marrakech, Morocco",
    "Rio de Janeiro, Brazil",
    "Queenstown, New Zealand",
    "Barcelona, Spain",
    "Cape Town, South Africa",
    "Reykjavik, Iceland",
    "Amsterdam, Netherlands",
    "Bora Bora, French Polynesia",
    "Venice, Italy",
    "Dubrovnik, Croatia",
    "Prague, Czech Republic",
    "Cappadocia, Turkey",
    "Grand Canyon, USA",
    "Machu Picchu, Peru",
    "Dubai, UAE",
    "Sydney, Australia",
    "Bangkok, Thailand",
    "Bali, Indonesia",
    "St. Petersburg, Russia",
    "Havana, Cuba",
    "Munich, Germany",
    "Edinburgh, Scotland",
    "Zurich, Switzerland",
    "Cairo, Egypt",
    "Copenhagen, Denmark",
    "Montreal, Canada",
    "Rome, Italy",
    "Kyiv, Ukraine",
    "Cusco, Peru",
    "Seoul, South Korea",
    "Auckland, New Zealand",
    "Vancouver, Canada",
    "Tokyo, Japan",
    "Istanbul, Turkey",
    "Bariloche, Argentina",
    "Budapest, Hungary",
    "Hanoi, Vietnam",
    "Delhi, India",
    "Lisbon, Portugal",
    "Cologne, Germany",
    "Krakow, Poland",
    "Athens, Greece",
    "Oslo, Norway",
    "Helsinki, Finland",
    "Stockholm, Sweden",
    "Moscow, Russia",
    "San Francisco, USA",
    "Los Angeles, USA",
    "Toronto, Canada",
    "Melbourne, Australia",
    "Agra, India",
    "Jaipur, India",
    "Queenstown, New Zealand",
    "Wellington, New Zealand",
    "Phuket, Thailand",
    "Nairobi, Kenya",
    "Casablanca, Morocco",
    "Hobart, Australia",
    "Perth, Australia",
    "Mumbai, India",
    "Amman, Jordan",
    "Capri, Italy",
    "Nice, France",
    "Bruges, Belgium",
    "Sapporo, Japan",
    "Seville, Spain",
    "Shanghai, China",
    "Xi'an, China",
    "Chiang Mai, Thailand",
    "Antigua, Guatemala",
    "Maldives",
    "Seychelles",
    "Fiji",
    "Zanzibar, Tanzania",
    "Galapagos Islands, Ecuador",
    "Madrid, Spain",
    "Cordoba, Argentina",
    "Manila, Philippines",
    "Lima, Peru",
    "Santiago, Chile",
    "Valletta, Malta",
    "Tbilisi, Georgia",
    "Casablanca, Morocco",
    "Naples, Italy",
    "Salzburg, Austria",
    "Sofia, Bulgaria",
    "Brisbane, Australia",
    "Jerusalem, Israel",
    "Buenos Aires, Argentina",
    "Riga, Latvia",
    "Vilnius, Lithuania",
    "Tallinn, Estonia",
    "Warsaw, Poland",
    "Bratislava, Slovakia",
    "Ljubljana, Slovenia",
    "Podgorica, Montenegro",
    "Skopje, North Macedonia",
    "Tirana, Albania",
    "Prishtina, Kosovo",
    "Sarajevo, Bosnia and Herzegovina",
    "Belgrade, Serbia",
    "Zagreb, Croatia",
    "Valencia, Spain",
    "Granada, Spain",
    "Cordoba, Spain",
    "Malaga, Spain",
    "Bilbao, Spain",
    "San Sebastian, Spain",
    "Toledo, Spain",
    "Valletta, Malta",
    "Split, Croatia",
    "Brno, Czech Republic",
    "Ostrava, Czech Republic",
    "Olomouc, Czech Republic",
    "Plitvice Lakes National Park, Croatia",
    "Hallstatt, Austria",
    "Innsbruck, Austria",
    "Salzburg, Austria",
    "Bled, Slovenia",
    "Ljubljana, Slovenia",
    "Zadar, Croatia",
    "Zagreb, Croatia",
    "Rovinj, Croatia",
    "Piran, Slovenia",
    "Lake Bled, Slovenia",
    "Ljubljana, Slovenia",
    "Porto, Portugal",
    "Lisbon, Portugal",
    "Sintra, Portugal",
    "Faro, Portugal",
    "Ponta Delgada, Portugal",
    "Horta, Portugal",
    "Santa Cruz, Portugal",
    "Pico Island, Portugal",
    "Angra do Heroísmo, Portugal",
    "Funchal, Portugal",
    "Ponta Delgada, Portugal",
    "Horta, Portugal",
    "Santa Cruz, Portugal",
    "Pico Island, Portugal",
    "Angra do Heroísmo, Portugal",
    "Funchal, Portugal",
    "San Marino",
    "Vatican City",
    "Sofia, Bulgaria",
    "Plovdiv, Bulgaria",
    "Rila Monastery, Bulgaria",
    "Veliko Tarnovo, Bulgaria",
    "Varna, Bulgaria",
    "Burgas, Bulgaria",
    "Sunny Beach, Bulgaria",
    "Golden Sands, Bulgaria",
    "Nesebar, Bulgaria",
    "Balchik, Bulgaria",
    "Sozopol, Bulgaria"
  ];
  
  